const fs = require('fs');
const path = process.argv[2];
let s = fs.readFileSync(path, 'utf8');
const nl = s.includes('\r\n') ? '\r\n' : '\n';
function repl(old, neu, label) {
  const oldN = old.split('\n').join(nl);
  const neuN = neu.split('\n').join(nl);
  const count = s.split(oldN).length - 1;
  if (count === 0) throw new Error('anchor not found: ' + label);
  if (count > 1) throw new Error('anchor ambiguous (' + count + '): ' + label);
  s = s.replace(oldN, neuN);
}

repl(
  [
    'using System.Security.Claims;',
    'using Microsoft.AspNetCore.Http;',
    'using Microsoft.EntityFrameworkCore;',
    'using Zelo.Contracts;',
  ].join('\n'),
  [
    'using System.Security.Claims;',
    'using Microsoft.AspNetCore.Http;',
    'using Microsoft.EntityFrameworkCore;',
    'using Npgsql;',
    'using Zelo.Contracts;',
  ].join('\n'),
  'usings',
);

repl(
  [
    '    public static async Task<IResult> CreateVehicle(',
    '        Guid householdId, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, IObjectStorage storage, CancellationToken ct)',
    '    {',
    '        var vehicle = await CreateVehicleEntityAsync(householdId, request, db, events, ct);',
    '        return Results.Created($"/api/auto/vehicles/{vehicle.Id}", VehicleResponse.From(vehicle, storage));',
    '    }',
    '',
    '    /// Construcao/persistencia partilhada entre CreateVehicle, ConfirmImport',
    '    /// e AutoMcpTools.CreateVehicle - todas precisam exatamente da mesma',
    '    /// logica (entidade + sync de inspecao + eventos), so a primeira devolve',
    '    /// um IResult.',
    '    internal static async Task<Vehicle> CreateVehicleEntityAsync(',
    '        Guid householdId, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, CancellationToken ct)',
    '    {',
    '        var vehicle = new Vehicle',
    '        {',
    '            Id = Guid.NewGuid(),',
    '            HouseholdId = householdId,',
    '            Category = request.Category,',
    '            Brand = request.Brand,',
    '            Model = request.Model,',
    '            Plate = request.Plate,',
    '            Vin = request.Vin,',
    '            Color = request.Color,',
    '            Driver = request.Driver,',
    '            Odometer = request.Odometer,',
    '            Registered = request.Registered,',
    '            NextInspection = request.NextInspection,',
    '            Insurer = request.Insurer,',
    '            InsurancePolicyNumber = request.InsurancePolicyNumber,',
    '            InsurancePeriodStart = request.InsurancePeriodStart,',
    '            InsurancePeriodEnd = request.InsurancePeriodEnd,',
    '            InsurancePremium = request.InsurancePremium,',
    '            IucDueDate = request.IucDueDate,',
    '            CreatedAt = DateTimeOffset.UtcNow,',
    '        };',
    '',
    '        db.Vehicles.Add(vehicle);',
    '        await db.SaveChangesAsync(ct);',
    '',
    '        await events.PublishAsync(VehicleEvents.Created(vehicle), ct);',
  ].join('\n'),
  [
    '    public static async Task<IResult> CreateVehicle(',
    '        Guid householdId, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, IObjectStorage storage, CancellationToken ct)',
    '    {',
    '        try',
    '        {',
    '            var vehicle = await CreateVehicleEntityAsync(householdId, request, db, events, ct);',
    '            return Results.Created($"/api/auto/vehicles/{vehicle.Id}", VehicleResponse.From(vehicle, storage));',
    '        }',
    '        catch (ArgumentException ex)',
    '        {',
    '            return Results.BadRequest(new { error = ex.Message });',
    '        }',
    '    }',
    '',
    '    /// Construcao/persistencia partilhada entre CreateVehicle, ConfirmImport',
    '    /// e AutoMcpTools.CreateVehicle - todas precisam exatamente da mesma',
    '    /// logica (entidade + sync de inspecao + eventos + validacao), so a',
    '    /// primeira devolve um IResult. Lanca ArgumentException (ver',
    '    /// VehicleValidation) - quem chama decide como traduzir isso.',
    '    internal static async Task<Vehicle> CreateVehicleEntityAsync(',
    '        Guid householdId, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, CancellationToken ct)',
    '    {',
    '        VehicleValidation.Validate(request);',
    '',
    '        var vehicle = new Vehicle',
    '        {',
    '            Id = Guid.NewGuid(),',
    '            HouseholdId = householdId,',
    '            Category = request.Category,',
    '            Brand = request.Brand,',
    '            Model = request.Model,',
    '            Plate = request.Plate,',
    '            Vin = request.Vin,',
    '            Color = request.Color,',
    '            Driver = request.Driver,',
    '            Odometer = request.Odometer,',
    '            Registered = request.Registered,',
    '            NextInspection = request.NextInspection,',
    '            Insurer = request.Insurer,',
    '            InsurancePolicyNumber = request.InsurancePolicyNumber,',
    '            InsurancePeriodStart = request.InsurancePeriodStart,',
    '            InsurancePeriodEnd = request.InsurancePeriodEnd,',
    '            InsurancePremium = request.InsurancePremium,',
    '            IucDueDate = request.IucDueDate,',
    '            CreatedAt = DateTimeOffset.UtcNow,',
    '        };',
    '',
    '        db.Vehicles.Add(vehicle);',
    '        await SaveOrThrowOnDuplicatePlateAsync(db, ct);',
    '',
    '        await events.PublishAsync(VehicleEvents.Created(vehicle), ct);',
  ].join('\n'),
  'CreateVehicle/CreateVehicleEntityAsync',
);

repl(
  [
    '    public static async Task<IResult> UpdateVehicle(',
    '        Guid id, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, IObjectStorage storage, CancellationToken ct)',
    '    {',
    '        var vehicle = await UpdateVehicleEntityAsync(id, request, db, events, ct);',
    '        return vehicle is null ? Results.NotFound() : Results.Ok(VehicleResponse.From(vehicle, storage));',
    '    }',
    '',
    '    /// Partilhada com AutoMcpTools.UpdateVehicle - devolve null (em vez de',
    '    /// IResult) para quem chama nao depender de tipos de Minimal API.',
    '    internal static async Task<Vehicle?> UpdateVehicleEntityAsync(',
    '        Guid id, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, CancellationToken ct)',
    '    {',
    '        var vehicle = await db.Vehicles.FindAsync([id], ct);',
    '        if (vehicle is null)',
    '            return null;',
  ].join('\n'),
  [
    '    public static async Task<IResult> UpdateVehicle(',
    '        Guid id, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, IObjectStorage storage, CancellationToken ct)',
    '    {',
    '        try',
    '        {',
    '            var vehicle = await UpdateVehicleEntityAsync(id, request, db, events, ct);',
    '            return vehicle is null ? Results.NotFound() : Results.Ok(VehicleResponse.From(vehicle, storage));',
    '        }',
    '        catch (ArgumentException ex)',
    '        {',
    '            return Results.BadRequest(new { error = ex.Message });',
    '        }',
    '    }',
    '',
    '    /// Partilhada com AutoMcpTools.UpdateVehicle - devolve null (em vez de',
    '    /// IResult) para quem chama nao depender de tipos de Minimal API. Lanca',
    '    /// ArgumentException (ver VehicleValidation) - quem chama decide como',
    '    /// traduzir isso.',
    '    internal static async Task<Vehicle?> UpdateVehicleEntityAsync(',
    '        Guid id, VehicleUpsertRequest request, AutoDbContext db, IEventPublisher events, CancellationToken ct)',
    '    {',
    '        var vehicle = await db.Vehicles.FindAsync([id], ct);',
    '        if (vehicle is null)',
    '            return null;',
    '',
    '        VehicleValidation.Validate(request);',
  ].join('\n'),
  'UpdateVehicle/UpdateVehicleEntityAsync',
);

fs.writeFileSync(path, s);
console.log('ok');
