// Re-export shadcn components with Z prefix for backward compatibility
export { default as ZButton } from './shadcn/Button.vue'
export { default as ZCard } from './shadcn/Card.vue'
export { default as ZCardHeader } from './shadcn/CardHeader.vue'
export { default as ZCardContent } from './shadcn/CardContent.vue'
export { default as ZInput } from './shadcn/Input.vue'
export { default as ZAvatar } from './shadcn/Avatar.vue'

// Re-export other existing components
export { default as ZStatusBadge } from './ZStatusBadge.vue'
export { default as ZStatGroup } from './ZStatGroup.vue'
export { default as ZSectionLabel } from './ZSectionLabel.vue'
export { default as ZSearchInput } from './ZSearchInput.vue'
export { default as ZEntityGroup } from './ZEntityGroup.vue'
export { default as ZSegmentedBar } from './ZSegmentedBar.vue'
export { default as ZSegmentedControl } from './ZSegmentedControl.vue'
export { default as ZTable } from './ZTable.vue'
export { default as ZStat } from './ZStat.vue'
export { default as ZSidePanel } from './ZSidePanel.vue'
export { default as ZWorkspace } from './ZWorkspace.vue'
export { default as ZEntityItem } from './ZEntityItem.vue'
export { default as ZBarChart } from './ZBarChart.vue'
export { default as ZNavRail } from './ZNavRail.vue'
export { default as ZPageHeader } from './ZPageHeader.vue'
export { default as ZDetailGrid } from './ZDetailGrid.vue'
