<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Zelo.SharedKernel\Zelo.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Zelo.Contracts\Zelo.Contracts.csproj" />
    <ProjectReference Include="..\..\Zelo.Messaging\Zelo.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
