<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Zelo.Messaging\Zelo.Messaging.csproj" />
    <ProjectReference Include="..\..\src\Modules\Zelo.Modules.Identity\Zelo.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Zelo.Modules.Core\Zelo.Modules.Core.csproj" />
    <ProjectReference Include="..\..\src\Modules\Zelo.Modules.Auto\Zelo.Modules.Auto.csproj" />
    <ProjectReference Include="..\..\src\Modules\Zelo.Modules.Inventory\Zelo.Modules.Inventory.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
</Project>
